# Generated by Django 5.0.7 on 2024-07-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_inventory_warehouse_delete_warehouse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
