# Generated by Django 5.0.7 on 2024-08-01 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_saleitem_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('total_quantity', models.IntegerField()),
                ('total_amount', models.FloatField()),
                ('percentage', models.FloatField()),
                ('sales_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.salesreport')),
            ],
        ),
    ]
